version: '3.8'

services:
  web:
    image: iti-pdfer
    #privileged: true
    build: 
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    expose:
      - '8080'
    restart: unless-stopped
    volumes:
      - data:/iti/store
    networks:
      - traefik
    #deploy:
    #  replicas: 5
    #labels:
    #  - "traefik.http.routers.web.rule=Host(`web.localhost`)"
    #  - "traefik.http.services.web.loadbalancer.server.port=8080"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - 'C:/Users/ofici/iti/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prometheus-data:/prometheus'
    networks:
      - prometheus-network
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    ports:
      - '3030:3030'
    container_name: grafana
    restart: unless-stopped
    #depends_on:
    #  - prometheus
    networks:
      - prometheus-network
    volumes:
      - 'C:/Users/ofici/iti/grafana/grafana.ini:/etc/grafana/grafana.ini'
      - grafana-data:/var/lib/grafana
  
  node_exporter:
    image: prom/node-exporter:latest 
    container_name: node_exporter
    pid: host
    ports:
      - "9100:9100/tcp"
    restart: unless-stopped
    volumes: #/:/host:ro,rslave
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    command:
      - '--path.procfs=/host/proc' 
      - '--path.rootfs=/rootfs' 
      - '--path.sysfs=/host/sys' 
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)' 
    #network_mode: host
    networks:
      - prometheus-network

  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:latest 
    container_name: cadvisor 
    ports: 
      - 8081:8080
    networks: 
      - prometheus-network 
    volumes: 
      - /:/rootfs:ro 
      - /var/run:/var/run:rw 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 
    depends_on: 
      - redis 

  redis: 
    image: redis:latest 
    container_name: redis 
    ports: 
      - 6379:6379 
    networks: 
      - prometheus-network
  
  traefik:
    image: traefik
    ports:
      - "80:80"
      - "8089:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dyn.yml:/etc/traefik/conf/dyn.yml:ro
    networks:
      - traefik

      
    #networks:
     # traefik:
     #   ipv4_address: 192.168.20.6



networks:
  prometheus-network:
    driver: bridge
  traefik:
    driver: bridge

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  data:
    driver: local
    driver_opts:
      type: cifs
      device: "//192.168.20.6/smb01"
      o: "username=francisco,password=root"