entryPoints:
  web:
    address: :80

providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    directory: /etc/traefik/conf/
    watch: true

api:
  insecure: true
  dashboard: true

log:
  level: INFO

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

accessLog:
  filePath: "/accessLogs/access.log"